### PR TITLE
Initializer accepts email as username

### PR DESCRIPTION
**Pull request by thetuxracer**

### CODE REVIEW

**Comment by thetuxracer** [comment]
#31.1 failed but #31.2 passed teh same test, not sure whats going on.

**Comment by dmacvicar** [comment]
Hi! Thanks for your contribution.

I don't understand this PR. The summary says it accepts email as username, however I see in the code:

* Ability to put the username outside of the url
* Ability pass credentials as ENV variable

How is email as username not working already? Does it work encoded with `%40`?

* What are the new semantics? What happens if the url has credentials and additionally credentials are passed with the new arguments?

* Also, I dislike the two new arguments. If I was to add them (which I am not convinced why they are needed), I would use a `opts={}` argument.

**Comment by dmacvicar** [comment]
Ok,  I just saw https://github.com/dmacvicar/bicho/issues/18 which answers one question for me. (`How is email as username not working already? Does it work encoded with %40?`)

**Comment by dmacvicar** [comment]
How did you test this code? A simple test case fails in the same way:

```ruby
require_relative 'helper'

class ClientTest < Minitest::Test
  def setup
    Bicho.client = nil
  end

 def test_email_as_username
    client = Bicho::Client.new('https://some%40redhat.com:password@bugzilla.redhat.com', "some@redhat.com", "password")
  end
end
```

```
[1] pry(#<Bicho::Client>)>
ERROR["test_email_as_username", ClientTest, 3.6431044040073175]
 test_email_as_username#ClientTest (3.64s)
XMLRPC::FaultException:         XMLRPC::FaultException: The username or password you entered is not valid.
            /home/duncan/.rbenv/versions/2.3.1/lib64/ruby/2.3.0/xmlrpc/client.rb:272:in `call'
            /space/git/dmacvicar.github.com/bicho/lib/bicho/client.rb:149:in `initialize'
            test/test_client.rb:25:in `new'
            test/test_client.rb:25:in `test_email_as_username'
```

Giving that this error is thrown at https://github.com/ruby/xmlrpc/blob/master/lib/xmlrpc/client.rb#L267 I think this is really the error of a wrong password generated by the `User.login` call at the server side.

**Comment by dmacvicar** [comment]
Closing as timeout.

**Pull request closed without merging**
